version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: pearmonie
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      NODE_ENV: "development"
      DATABASE_URL: "postgres://holaitan4:FJfB3UNzAQ2o@ep-noisy-water-113541.us-east-2.aws.neon.tech/pearmonie"
    networks:
      - backend-network

  db:
    image: postgres:alpine
    container_name: pearmonie-db
    environment:
      POSTGRES_USER: holaitan4
      POSTGRES_PASSWORD: FJfB3UNzAQ2o
      POSTGRES_DB: pearmonie 
    ports:
      - "5432:5432"
    networks:
      - backend-network

  redis:
    image: "redis:alpine"
    container_name: "pearmonie-redis"
    ports:
      - "6380:6379"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
